/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.awt.Color;
import java.awt.Shape;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author silas
 */
public class Program extends javax.swing.JFrame {

    /**
     * Creates new form Program
     */
    public Program() {
        initComponents();

        themeDefault.setActionCommand("Windows");
        themeNimbus.setActionCommand("Nimbus");
        themeMetal.setActionCommand("Metal");
        selectedTheme = buttonGroup1.getSelection();
    }

    //Número que será gerado nas ações dos botões
    public double numberVal = 0.0;
    public boolean nextNumber;
    public Character option = null;
    private ButtonModel selectedTheme;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fieldResult = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        numberButton7 = new javax.swing.JButton();
        numberButton8 = new javax.swing.JButton();
        numberButton9 = new javax.swing.JButton();
        numberButton4 = new javax.swing.JButton();
        numberButton5 = new javax.swing.JButton();
        numberButton6 = new javax.swing.JButton();
        numberButton1 = new javax.swing.JButton();
        numberButton2 = new javax.swing.JButton();
        numberButton3 = new javax.swing.JButton();
        buttonPonto = new javax.swing.JButton();
        numberButton0 = new javax.swing.JButton();
        buttonIgual = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonC = new javax.swing.JButton();
        buttonMais = new javax.swing.JButton();
        buttonMenos = new javax.swing.JButton();
        buttonVezes = new javax.swing.JButton();
        buttonDivisao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        themeDefault = new javax.swing.JRadioButtonMenuItem();
        themeNimbus = new javax.swing.JRadioButtonMenuItem();
        themeMetal = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        fieldResult.setEditable(false);
        fieldResult.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fieldResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldResult.setText("0");
        fieldResult.setPreferredSize(new java.awt.Dimension(260, 60));
        fieldResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldResultActionPerformed(evt);
            }
        });
        jPanel1.add(fieldResult);

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        numberButton7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton7.setText("7");
        numberButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton7);

        numberButton8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton8.setText("8");
        numberButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton8);

        numberButton9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton9.setText("9");
        numberButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton9);

        numberButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton4.setText("4");
        numberButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton4);

        numberButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton5.setText("5");
        numberButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton5);

        numberButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton6.setText("6");
        numberButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton6);

        numberButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton1.setText("1");
        numberButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton1);

        numberButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton2.setText("2");
        numberButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton2);

        numberButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton3.setText("3");
        numberButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton3);

        buttonPonto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonPonto.setText(",");
        buttonPonto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(buttonPonto);

        numberButton0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numberButton0.setText("0");
        numberButton0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButton0ActionPerformed(evt);
            }
        });
        jPanel2.add(numberButton0);

        buttonIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonIgual.setText("=");
        buttonIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIgualActionPerformed(evt);
            }
        });
        jPanel2.add(buttonIgual);

        jPanel3.setLayout(new java.awt.GridLayout(5, 0));

        buttonC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonC.setText("C");
        buttonC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });
        jPanel3.add(buttonC);

        buttonMais.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonMais.setText("+");
        buttonMais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMaisActionPerformed(evt);
            }
        });
        jPanel3.add(buttonMais);

        buttonMenos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonMenos.setText("-");
        buttonMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(buttonMenos);

        buttonVezes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonVezes.setText("x");
        buttonVezes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(buttonVezes);

        buttonDivisao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonDivisao.setText("÷");
        jPanel3.add(buttonDivisao);

        jMenu1.setText("Opções");

        jMenuItem1.setText("Opção 1");
        jMenu1.add(jMenuItem1);

        jMenu3.setText("Tema");
        jMenu3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jMenu3FocusLost(evt);
            }
        });

        buttonGroup1.add(themeDefault);
        themeDefault.setSelected(true);
        themeDefault.setText("Padrão");
        themeDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeDefaultActionPerformed(evt);
            }
        });
        jMenu3.add(themeDefault);

        buttonGroup1.add(themeNimbus);
        themeNimbus.setText("Nimbus");
        themeNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeNimbusActionPerformed(evt);
            }
        });
        jMenu3.add(themeNimbus);

        buttonGroup1.add(themeMetal);
        themeMetal.setText("Metal");
        themeMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeMetalActionPerformed(evt);
            }
        });
        jMenu3.add(themeMetal);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldResultActionPerformed

    }//GEN-LAST:event_fieldResultActionPerformed

    private void numberButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton1ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "1", nextNumber);
    }//GEN-LAST:event_numberButton1ActionPerformed

    private void buttonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIgualActionPerformed

    }//GEN-LAST:event_buttonIgualActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        fieldResult.setText("0");
        numberVal = 0.0;
    }//GEN-LAST:event_buttonCActionPerformed

    private void numberButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton2ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "2", nextNumber);
    }//GEN-LAST:event_numberButton2ActionPerformed

    private void numberButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton3ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "3", nextNumber);
    }//GEN-LAST:event_numberButton3ActionPerformed

    private void numberButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton4ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "4", nextNumber);
    }//GEN-LAST:event_numberButton4ActionPerformed

    private void numberButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton5ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "5", nextNumber);
    }//GEN-LAST:event_numberButton5ActionPerformed

    private void numberButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton6ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "6", nextNumber);
    }//GEN-LAST:event_numberButton6ActionPerformed

    private void numberButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton7ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "7", nextNumber);
    }//GEN-LAST:event_numberButton7ActionPerformed

    private void numberButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton8ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "8", nextNumber);
    }//GEN-LAST:event_numberButton8ActionPerformed

    private void numberButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton9ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "9", nextNumber);
    }//GEN-LAST:event_numberButton9ActionPerformed

    private void numberButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButton0ActionPerformed
        nextNumber = ControllerNumeros.numbersButtons(fieldResult, "0", nextNumber);
    }//GEN-LAST:event_numberButton0ActionPerformed

    private void buttonMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMaisActionPerformed
        if (!fieldResult.getText().equals("0") && fieldResult.getText() != null) {

            numberVal = numberVal + Double.parseDouble(fieldResult.getText());
            if (ControllerNumeros.hasDecimalPoint(numberVal)) {
                fieldResult.setText(String.valueOf(numberVal));
            } else {
                fieldResult.setText(String.valueOf((int) numberVal));
            }
            nextNumber = true;
        }
    }//GEN-LAST:event_buttonMaisActionPerformed

    private void jMenu3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenu3FocusLost
        
    }//GEN-LAST:event_jMenu3FocusLost

    private void themeDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeDefaultActionPerformed
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
            selectedTheme = buttonGroup1.getSelection();
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_themeDefaultActionPerformed

    private void themeNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeNimbusActionPerformed
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
            selectedTheme = buttonGroup1.getSelection();
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_themeNimbusActionPerformed

    private void themeMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeMetalActionPerformed
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
            selectedTheme = buttonGroup1.getSelection();
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_themeMetalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new Program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonDivisao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonIgual;
    private javax.swing.JButton buttonMais;
    private javax.swing.JButton buttonMenos;
    private javax.swing.JButton buttonPonto;
    private javax.swing.JButton buttonVezes;
    private javax.swing.JTextField fieldResult;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton numberButton0;
    private javax.swing.JButton numberButton1;
    private javax.swing.JButton numberButton2;
    private javax.swing.JButton numberButton3;
    private javax.swing.JButton numberButton4;
    private javax.swing.JButton numberButton5;
    private javax.swing.JButton numberButton6;
    private javax.swing.JButton numberButton7;
    private javax.swing.JButton numberButton8;
    private javax.swing.JButton numberButton9;
    private javax.swing.JRadioButtonMenuItem themeDefault;
    private javax.swing.JRadioButtonMenuItem themeMetal;
    private javax.swing.JRadioButtonMenuItem themeNimbus;
    // End of variables declaration//GEN-END:variables

}
